# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a35904aeea8c5afa0bcd66d3ad6d86b96b1ad47fe713e664b1c497a95351ea8c575f48b63c8cabbe7a05f1363865d903007495fa6743f07a34814afe031a8f8

test:
  secret_key_base: 8d229e2fcfdbd60c00466cb8ba3f2fb3fe52abaf403aeeabb0560932f90b28e8d9ff876a96a7523435c371726374ba39d16db84d83d5ad21a169cbf3c59de26e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
