# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8405c9e902e871fe196956ff8f373f3a1cac6a0b04666b2b48de06f3d77397d89cb87dfc06d315b71c868cec9434777fc19143eb5805c97134332b5744dd65a

test:
  secret_key_base: 2c3b614a4618e5153804034af056e44ee0cbb1fc6df7fe9f7aad9c0682c4564cd0bcd9e199ae98376af80bcacdb6bf38be2af1e44924b59a41d752f1833779f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
